import { Chapter, Target } from '../types';

export const TARGETS: Target[] = [
  // Chapter A: Order Politely (Beginner)
  {
    id: 'order.item',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'Un café, por favor.',
    english: 'A coffee, please.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['cafe', 'ordering', 'essentials'],
    explanation: 'Basic polite request using "por favor".',
  },
  {
    id: 'order.polite',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'Ponme un café con leche, por favor.',
    english: 'A white coffee for me, please (lit. Put me a coffee with milk).',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['order.item'],
    tags: ['cafe', 'polite', 'chunks', 'ponme'],
    explanation: 'In Spain, "Ponme..." is standard, warm, and natural at any bar counter.',
  },
  {
    id: 'order.quantity',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'Dos cafés y un agua, por favor.',
    english: 'Two coffees and a water, please.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: ['order.item'],
    tags: ['cafe', 'quantities'],
    explanation: 'Combining multiple items with numbers.',
  },
  {
    id: 'order.modifier',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'Un cortado con leche fría.',
    english: 'An espresso with a dash of cold milk.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: ['order.item'],
    tags: ['cafe', 'modifiers'],
    explanation: 'Specifying how you like your drink in Spain (solo, cortado, con leche).',
  },
  {
    id: 'order.bill',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'La cuenta, por favor.',
    english: 'The bill, please.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['cafe', 'bill', 'paying'],
    explanation: 'Standard request to ask for the bill at the end of service.',
  },
  {
    id: 'order.table',
    revision: 1,
    packId: 'chapter-a',
    type: 'phrase',
    spanish: 'Una mesa para dos, por favor.',
    english: 'A table for two, please.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['restaurant', 'table'],
    explanation: 'Requesting seating upon entering a restaurant or terrace.',
  },

  // Chapter B: What was happening? (Intermediate)
  {
    id: 'past.progressive-action',
    revision: 1,
    packId: 'chapter-b',
    type: 'construction',
    spanish: 'Estaba cocinando.',
    english: 'I was cooking.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['grammar', 'past-continuous', 'estaba-gerundio'],
    explanation: '"Estar + gerundio" describes an activity ongoing in the past.',
  },
  {
    id: 'past.progressive-question',
    revision: 1,
    packId: 'chapter-b',
    type: 'construction',
    spanish: '¿Qué estabas haciendo?',
    english: 'What were you doing?',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['past.progressive-action'],
    tags: ['grammar', 'questions', 'past'],
    explanation: 'Asking an interlocutor what activity was in progress.',
  },
  {
    id: 'past.progressive-group',
    revision: 1,
    packId: 'chapter-b',
    type: 'construction',
    spanish: 'Estábamos cenando.',
    english: 'We were having dinner.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: ['past.progressive-action'],
    tags: ['grammar', 'we', 'past-continuous'],
    explanation: 'Using the 1st person plural (nosotros) past progressive.',
  },
  {
    id: 'past.progressive-interrupt',
    revision: 1,
    packId: 'chapter-b',
    type: 'construction',
    spanish: 'Estaba estudiando cuando llamaste.',
    english: 'I was studying when you called.',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['past.progressive-action'],
    tags: ['grammar', 'interrupting', 'preterite-vs-imperfect'],
    explanation: 'The background ongoing action (estaba estudiando) interrupted by a completed action (llamaste).',
  },
  {
    id: 'past.simultaneous',
    revision: 1,
    packId: 'chapter-b',
    type: 'construction',
    spanish: 'Mientras yo cocinaba, él ponía la mesa.',
    english: 'While I was cooking, he was setting the table.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: ['past.progressive-action'],
    tags: ['grammar', 'simultaneous', 'mientras'],
    explanation: 'Two parallel ongoing background events in the past.',
  },
  {
    id: 'past.habitual-vs-prog',
    revision: 1,
    packId: 'chapter-b',
    type: 'contrast',
    spanish: 'Los domingos comíamos juntos.',
    english: 'On Sundays we used to eat together.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['grammar', 'habitual', 'imperfect'],
    explanation: 'Habitual past actions use simple imperfect (comíamos), not estar + gerundio.',
  },

  // Chapter C: If I had more time… (Advanced)
  {
    id: 'hypo.time-money',
    revision: 1,
    packId: 'chapter-c',
    type: 'construction',
    spanish: 'Si tuviera más tiempo, viajaría más.',
    english: 'If I had more time, I would travel more.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['grammar', 'subjunctive', 'second-conditional'],
    explanation: 'Si + imperfect subjunctive (tuviera/tuviese) + conditional (viajaría) for hypothetical present/future.',
  },
  {
    id: 'hypo.able-to-act',
    revision: 1,
    packId: 'chapter-c',
    type: 'construction',
    spanish: 'Si pudiera elegir, viviría cerca del mar.',
    english: 'If I could choose, I would live near the sea.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: ['hypo.time-money'],
    tags: ['grammar', 'pudiera', 'conditional'],
    explanation: 'Expressing an imagined ability or freedom to choose.',
  },
  {
    id: 'hypo.situation',
    revision: 1,
    packId: 'chapter-c',
    type: 'construction',
    spanish: 'Si estuviera en tu lugar, no me preocuparía.',
    english: 'If I were in your place, I would not worry.',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['hypo.time-money'],
    tags: ['grammar', 'estuviera', 'advice'],
    explanation: 'Imagining a different situation or perspective with "estuviera".',
  },
  {
    id: 'hypo.advice',
    revision: 1,
    packId: 'chapter-c',
    type: 'phrase',
    spanish: 'Si fuera tú, hablaría con ella.',
    english: 'If I were you, I would speak with her.',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['hypo.time-money'],
    tags: ['advice', 'ser-subjunctive'],
    explanation: 'The classic formula "Yo que tú..." or "Si fuera tú..." for tactful advice.',
  },
  {
    id: 'hypo.question',
    revision: 1,
    packId: 'chapter-c',
    type: 'construction',
    spanish: '¿Qué harías si ganaras la lotería?',
    english: 'What would you do if you won the lottery?',
    locale: 'es-ES',
    register: 'informal',
    prerequisiteIds: ['hypo.time-money'],
    tags: ['questions', 'hypothetical'],
    explanation: 'Asking someone about an imaginary scenario.',
  },
  {
    id: 'hypo.open-vs-unreal',
    revision: 1,
    packId: 'chapter-c',
    type: 'contrast',
    spanish: 'Si tengo tiempo, iré.',
    english: 'If I have time, I will go.',
    locale: 'es-ES',
    register: 'neutral-polite',
    prerequisiteIds: [],
    tags: ['grammar', 'real-vs-unreal', 'conditional'],
    explanation: 'Real/open condition uses present indicative + future, not subjunctive.',
  },
];

export const CHAPTERS: Chapter[] = [
  {
    id: 'chapter-a',
    title: 'Order politely',
    subtitle: 'Café & Restaurant Basics',
    band: 'Beginner',
    grammarAliases: ['order', 'cafe', 'por favor', 'ponme', 'food'],
    goal: 'Order drinks and food, request items, and ask for the bill with natural Spanish manners.',
    explanation: 'In Spain, ordering is direct, warm, and natural. Use authentic formulas like "¡Ponme un café!", "¿Me pones un cortado?" or simple requests with "por favor". Notice how drinks are specified: café solo, cortado, con leche, o con hielo.',
    examples: [
      { spanish: 'Ponme un café con leche, por favor.', english: 'A white coffee for me, please.' },
      { spanish: 'La cuenta, cuando puedas.', english: 'The bill, when you can.' },
    ],
    targetIds: [
      'order.item',
      'order.polite',
      'order.quantity',
      'order.modifier',
      'order.bill',
      'order.table',
    ],
    supportedGames: ['builder', 'tales', 'market', 'cafe', 'tapeo', 'listening'],
  },
  {
    id: 'chapter-b',
    title: 'What was happening?',
    subtitle: 'Past Continuous & Interruptions',
    band: 'Intermediate',
    grammarAliases: ['past continuous', 'past progressive', 'estaba + gerundio', 'imperfect'],
    goal: 'Describe ongoing background events and connect them with interrupting actions.',
    explanation: 'Use "estaba + gerundio" (estaba cocinando, estabas haciendo) when viewing an action from within its duration. When a sudden event cuts in, describe that event with the preterite: "...cuando llamaste". For recurring Sunday habits, prefer the simple imperfect.',
    examples: [
      { spanish: 'Estaba cocinando cuando sonó el teléfono.', english: 'I was cooking when the telephone rang.' },
      { spanish: '¿Qué estabas haciendo a las cinco?', english: 'What were you doing at five?' },
    ],
    targetIds: [
      'past.progressive-action',
      'past.progressive-question',
      'past.progressive-group',
      'past.progressive-interrupt',
      'past.simultaneous',
      'past.habitual-vs-prog',
    ],
    supportedGames: ['builder', 'tales', 'market', 'cafe', 'tapeo', 'listening'],
  },
  {
    id: 'chapter-c',
    title: 'If I had more time…',
    subtitle: 'Hypotheticals & Advice',
    band: 'Advanced',
    grammarAliases: ['imperfect subjunctive', 'second conditional', 'si tuviera', 'si fuera'],
    goal: 'Discuss imagined situations, express wishes, and give advice using subjunctive and conditional pairs.',
    explanation: 'To imagine unreal present or future scenarios, combine "si + imperfecto de subjuntivo" (tuviera, pudiera, fuera) with the conditional (viajaría, viviría, diría). Both "-ra" (tuviera) and "-se" (tuviese) forms are accepted in Spain, with "-ra" being the most widespread.',
    examples: [
      { spanish: 'Si tuviera más tiempo, aprendería a tocar la guitarra.', english: 'If I had more time, I would learn to play guitar.' },
      { spanish: 'Si fuera tú, no me preocuparía tanto.', english: 'If I were you, I would not worry so much.' },
    ],
    targetIds: [
      'hypo.time-money',
      'hypo.able-to-act',
      'hypo.situation',
      'hypo.advice',
      'hypo.question',
      'hypo.open-vs-unreal',
    ],
    supportedGames: ['builder', 'tales', 'market', 'cafe', 'tapeo', 'listening'],
  },
];
