import { AnyPrompt } from '../types';

export const ALL_PROMPTS: AnyPrompt[] = [
  // =========================================================================
  // 1. PHRASE BUILDER PROMPTS
  // =========================================================================
  {
    id: 'bld.order.bill.1',
    revision: 1,
    game: 'builder',
    targetId: 'order.bill',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Ask for the bill, please.',
    tiles: [
      { id: 't1', text: 'La' },
      { id: 't2', text: 'cuenta,' },
      { id: 't3', text: 'por' },
      { id: 't4', text: 'favor.' },
      { id: 't5', text: 'el' },
      { id: 't6', text: 'café' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'La cuenta, por favor.',
    explanation: 'Use "La cuenta, por favor" to ask for the bill at the end of your meal or drink.',
  },
  {
    id: 'bld.order.item.1',
    revision: 1,
    game: 'builder',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Order a coffee, please.',
    tiles: [
      { id: 't1', text: 'Un' },
      { id: 't2', text: 'café,' },
      { id: 't3', text: 'por' },
      { id: 't4', text: 'favor.' },
      { id: 't5', text: 'una' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'Un café, por favor.',
    explanation: '"Café" is masculine, so use "Un café". Add "por favor" for politeness.',
  },
  {
    id: 'bld.order.polite.1',
    revision: 1,
    game: 'builder',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Say politely: I would like a coffee with milk.',
    tiles: [
      { id: 't1', text: 'Quería' },
      { id: 't2', text: 'un' },
      { id: 't3', text: 'café' },
      { id: 't4', text: 'con' },
      { id: 't5', text: 'leche.' },
      { id: 't6', text: 'Quiero' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5'],
    ],
    validOffTargetSequences: [
      {
        sequence: ['t6', 't2', 't3', 't4', 't5'],
        feedback: 'Valid Spanish! However, "Quería" is softer and more typical in Spain.',
      },
    ],
    canonicalDisplay: 'Quería un café con leche.',
    explanation: '"Quería" softens your order into a polite request.',
  },
  {
    id: 'bld.order.table.1',
    revision: 1,
    game: 'builder',
    targetId: 'order.table',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Ask for a table for two, please.',
    tiles: [
      { id: 't1', text: 'Una' },
      { id: 't2', text: 'mesa' },
      { id: 't3', text: 'para' },
      { id: 't4', text: 'dos,' },
      { id: 't5', text: 'por' },
      { id: 't6', text: 'favor.' },
      { id: 't7', text: 'un' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
    ],
    canonicalDisplay: 'Una mesa para dos, por favor.',
    explanation: '"Mesa" is feminine: "Una mesa para dos, por favor."',
  },

  // Chapter B: What was happening? (Builder)
  {
    id: 'bld.past.interrupt.1',
    revision: 1,
    game: 'builder',
    targetId: 'past.progressive-interrupt',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Build: I was studying when you called.',
    tiles: [
      { id: 't1', text: 'Estaba' },
      { id: 't2', text: 'estudiando' },
      { id: 't3', text: 'cuando' },
      { id: 't4', text: 'llamaste.' },
      { id: 't5', text: 'llamabas' },
      { id: 't6', text: 'estudié' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'Estaba estudiando cuando llamaste.',
    explanation: 'Background ongoing action uses "estaba estudiando", interrupting completed event uses "llamaste".',
  },
  {
    id: 'bld.past.action.1',
    revision: 1,
    game: 'builder',
    targetId: 'past.progressive-action',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Build: I was cooking.',
    tiles: [
      { id: 't1', text: 'Estaba' },
      { id: 't2', text: 'cocinando.' },
      { id: 't3', text: 'Era' },
      { id: 't4', text: 'cocinar' },
    ],
    acceptedSequences: [
      ['t1', 't2'],
    ],
    canonicalDisplay: 'Estaba cocinando.',
    explanation: 'Form the past progressive with the imperfect of estar (estaba) + gerund (-ando/-iendo).',
  },
  {
    id: 'bld.past.group.1',
    revision: 1,
    game: 'builder',
    targetId: 'past.progressive-group',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Build: We were having dinner.',
    tiles: [
      { id: 't1', text: 'Estábamos' },
      { id: 't2', text: 'cenando.' },
      { id: 't3', text: 'Cenamos' },
      { id: 't4', text: 'Estaban' },
    ],
    acceptedSequences: [
      ['t1', 't2'],
    ],
    canonicalDisplay: 'Estábamos cenando.',
    explanation: '"Nosotros estábamos cenando" denotes an ongoing group dinner.',
  },

  // Chapter C: If I had more time… (Builder)
  {
    id: 'bld.hypo.time.1',
    revision: 1,
    game: 'builder',
    targetId: 'hypo.time-money',
    chapterId: 'chapter-c',
    evidence: 'scaffolded-production',
    supportLevel: 'stretch',
    intent: 'Build: If I had more time, I would travel more.',
    tiles: [
      { id: 't1', text: 'Si' },
      { id: 't2', text: 'tuviera' },
      { id: 't3', text: 'más' },
      { id: 't4', text: 'tiempo,' },
      { id: 't5', text: 'viajaría' },
      { id: 't6', text: 'más.' },
      { id: 't7', text: 'tengo' },
      { id: 't8', text: 'viajo' },
      { id: 't9', text: 'tuviese' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
      ['t1', 't9', 't3', 't4', 't5', 't6'], // tuviese variant accepted!
    ],
    canonicalDisplay: 'Si tuviera más tiempo, viajaría más.',
    explanation: 'Hypothetical conditions: "Si + imperfect subjunctive (tuviera/tuviese)" + "conditional (viajaría)".',
  },
  {
    id: 'bld.hypo.advice.1',
    revision: 1,
    game: 'builder',
    targetId: 'hypo.advice',
    chapterId: 'chapter-c',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Give advice: If I were you, I would speak with her.',
    tiles: [
      { id: 't1', text: 'Si' },
      { id: 't2', text: 'fuera' },
      { id: 't3', text: 'tú,' },
      { id: 't4', text: 'hablaría' },
      { id: 't5', text: 'con' },
      { id: 't6', text: 'ella.' },
      { id: 't7', text: 'era' },
      { id: 't8', text: 'fuese' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
      ['t1', 't8', 't3', 't4', 't5', 't6'],
    ],
    canonicalDisplay: 'Si fuera tú, hablaría con ella.',
    explanation: '"Si fuera tú, hablaría..." is the standard Spanish formula for offering gentle advice.',
  },

  // =========================================================================
  // 2. TINY TALES PROMPTS
  // =========================================================================
  {
    id: 'tls.cafe.counter.1',
    revision: 1,
    game: 'tales',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    title: 'Morning at the Bar',
    setting: 'A busy counter in Madrid with the aroma of freshly ground coffee.',
    turns: [
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: '¡Buenos días! ¿Qué va a ser?',
        goal: 'Order a coffee with milk politely.',
        choices: [
          {
            id: 'c1',
            text: 'Quería un café con leche, por favor.',
            isCorrect: true,
            feedback: 'Perfect! Warm, polite, and natural.',
            consequence: 'El camarero asiente con una sonrisa rápida y enciende la máquina de café.',
          },
          {
            id: 'c2',
            text: 'Dame café.',
            isCorrect: false,
            feedback: 'A bit too abrupt for an everyday counter.',
            consequence: 'El camarero te mira sorprendido por el tono directo.',
          },
        ],
      },
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: '¿Algo para picar? ¿Un cruasán o tostada con tomate?',
        goal: 'Politely ask for toast with tomato.',
        choices: [
          {
            id: 'c3',
            text: 'Una tostada con tomate, por favor.',
            isCorrect: true,
            feedback: 'Excellent choice. Classic Spanish breakfast.',
            consequence: 'Corta el pan de barra y lo pone a tostar crujiente.',
          },
          {
            id: 'c4',
            text: 'No comida nunca.',
            isCorrect: false,
            feedback: 'Grammatically confused. "Nada más, gracias" would fit.',
            consequence: 'El camarero no te entiende bien y espera.',
          },
        ],
      },
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: 'Aquí tienes. ¿Deseas algo más?',
        goal: 'Ask for the bill.',
        choices: [
          {
            id: 'c5',
            text: 'Nada más. La cuenta, por favor.',
            isCorrect: true,
            feedback: 'Exact formula for wrapping up.',
            consequence: 'Te deja el platito con el tique: «Son tres euros con cincuenta».',
          },
          {
            id: 'c6',
            text: '¿Cuánto dinero tú quieres?',
            isCorrect: false,
            feedback: 'Unnatural phrasing. Always use "La cuenta, por favor" or "¿Cuánto es?".',
            consequence: 'El camarero sonríe con paciencia y calcula la cuenta.',
          },
        ],
      },
    ],
    explanation: 'Polite interactions at a Spanish bar use short, polite chunks like "Quería..." and "La cuenta, por favor".',
  },
  {
    id: 'tls.past.call.1',
    revision: 1,
    game: 'tales',
    targetId: 'past.progressive-action',
    chapterId: 'chapter-b',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    title: 'The Missed Call',
    setting: 'You meet your friend Mateo on Calle Mayor.',
    turns: [
      {
        speaker: 'Mateo',
        speakerRole: 'friend',
        text: '¡Oye! Te llamé ayer a las siete y no contestaste. ¿Qué estabas haciendo?',
        goal: 'Explain that you were cooking when he called.',
        choices: [
          {
            id: 'c1',
            text: 'Estaba cocinando cuando llamaste.',
            isCorrect: true,
            feedback: 'Spot on! Ongoing action + interrupting preterite call.',
            consequence: 'Mateo asiente: «¡Ah, con razón no oías el teléfono!».',
          },
          {
            id: 'c2',
            text: 'Cociné mientras llamabas.',
            isCorrect: false,
            feedback: 'Reverses the aspect. The call was a point in time, cooking was ongoing.',
            consequence: 'Mateo parece algo confuso con los tiempos.',
          },
        ],
      },
      {
        speaker: 'Mateo',
        speakerRole: 'friend',
        text: '¿Y después cenasteis en casa?',
        goal: 'Say that you and your roommate were dining together.',
        choices: [
          {
            id: 'c3',
            text: 'Sí, estábamos cenando tranquilamente.',
            isCorrect: true,
            feedback: 'Good use of 1st person plural past continuous.',
            consequence: 'Mateo sonríe: «¡Qué bien! Yo terminé cenando una pizza fría».',
          },
          {
            id: 'c4',
            text: 'Cenábamos todos los días.',
            isCorrect: false,
            isOffTarget: true,
            feedback: 'Habitual imperfect doesn\'t answer about yesterday evening.',
            consequence: 'Mateo aclara: «Me refería a ayer, claro».',
          },
        ],
      },
    ],
    explanation: 'When explaining why you missed a past moment, describe the background activity with "estaba + gerundio".',
  },
  {
    id: 'tls.hypo.dream.1',
    revision: 1,
    game: 'tales',
    targetId: 'hypo.able-to-act',
    chapterId: 'chapter-c',
    evidence: 'meaning-recognition',
    supportLevel: 'stretch',
    title: 'Imagining the Future',
    setting: 'Relaxing on a sunny bench with Lucía in the Retiro park.',
    turns: [
      {
        speaker: 'Lucía',
        speakerRole: 'friend',
        text: 'Si pudieras mudarte a cualquier sitio mañana, ¿dónde vivirías?',
        goal: 'Express your wish to live near the sea if you could choose.',
        choices: [
          {
            id: 'c1',
            text: 'Si pudiera elegir, viviría cerca del mar.',
            isCorrect: true,
            feedback: 'Brilliant! "Si pudiera..." + conditional "viviría".',
            consequence: 'Lucía suspira: «¡Ojalá! El sonido de las olas todas las mañanas…».',
          },
          {
            id: 'c2',
            text: 'Si puedo elegir, vivo en el mar.',
            isCorrect: false,
            feedback: 'That uses present indicative for an open real condition rather than imagining an unreal wish.',
            consequence: 'Lucía sonríe: «Hablo de un sueño, ¡ojalá fuera tan fácil!».',
          },
        ],
      },
      {
        speaker: 'Lucía',
        speakerRole: 'friend',
        text: '¿Y qué harías con todo el tiempo libre?',
        goal: 'Say you would learn guitar if you had more time.',
        choices: [
          {
            id: 'c3',
            text: 'Si tuviera tiempo, aprendería a tocar la guitarra.',
            isCorrect: true,
            feedback: 'Flawless conditional pairing: tuviera + aprendería.',
            consequence: 'Lucía aplaude entusiasmada: «¡Pues darías conciertos en la playa!».',
          },
          {
            id: 'c4',
            text: 'Si tendría tiempo, aprendo guitarra.',
            isCorrect: false,
            feedback: 'Never use the conditional (tendría) right after "si". Use the imperfect subjunctive (tuviera).',
            consequence: 'Lucía capta la idea pero la construcción suena extraña.',
          },
        ],
      },
    ],
    explanation: 'Hypothetical situations pair "si + imperfect subjunctive" with the conditional consequence.',
  },

  // =========================================================================
  // 3. POCKET MARKET PROMPTS
  // =========================================================================
  {
    id: 'mkt.order.apple.1',
    revision: 1,
    game: 'market',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Put the apple in the shopping bag.',
    correctItemId: 'item-apple',
    choices: [
      { id: 'item-apple', spanish: 'la manzana', english: 'the apple', gender: 'la', icon: 'apple' },
      { id: 'item-bread', spanish: 'el pan', english: 'the bread', gender: 'el', icon: 'bread' },
      { id: 'item-water', spanish: 'el agua', english: 'the water', gender: 'el', icon: 'water' },
    ],
    explanation: '"Manzana" is feminine: "la manzana".',
  },
  {
    id: 'mkt.order.bread.1',
    revision: 1,
    game: 'market',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Put the bread in the shopping bag.',
    correctItemId: 'item-bread',
    choices: [
      { id: 'item-cheese', spanish: 'el queso', english: 'the cheese', gender: 'el', icon: 'cheese' },
      { id: 'item-bread', spanish: 'el pan', english: 'the bread', gender: 'el', icon: 'bread' },
      { id: 'item-milk', spanish: 'la leche', english: 'the milk', gender: 'la', icon: 'milk' },
    ],
    explanation: '"Pan" is masculine: "el pan".',
  },
  {
    id: 'mkt.order.water.1',
    revision: 1,
    game: 'market',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    instruction: 'Añade el agua a la bolsa.',
    correctItemId: 'item-water',
    choices: [
      { id: 'item-water', spanish: 'el agua', english: 'the water', gender: 'el', icon: 'water' },
      { id: 'item-orange', spanish: 'las naranjas', english: 'the oranges', gender: 'las', icon: 'orange' },
      { id: 'item-apple', spanish: 'la manzana', english: 'the apple', gender: 'la', icon: 'apple' },
    ],
    explanation: '"Agua" takes the masculine article "el agua" in the singular to prevent vowel clash, though the noun is feminine.',
  },
  {
    id: 'mkt.order.cheese.1',
    revision: 1,
    game: 'market',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Put the cheese in the shopping bag.',
    correctItemId: 'item-cheese',
    choices: [
      { id: 'item-bread', spanish: 'el pan', english: 'the bread', gender: 'el', icon: 'bread' },
      { id: 'item-cheese', spanish: 'el queso', english: 'the cheese', gender: 'el', icon: 'cheese' },
      { id: 'item-apple', spanish: 'la manzana', english: 'the apple', gender: 'la', icon: 'apple' },
    ],
    explanation: '"Queso" is masculine: "el queso".',
  },
  {
    id: 'mkt.order.oranges.1',
    revision: 1,
    game: 'market',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Put the oranges in the bag.',
    correctItemId: 'item-orange',
    choices: [
      { id: 'item-orange', spanish: 'las naranjas', english: 'the oranges', gender: 'las', icon: 'orange' },
      { id: 'item-water', spanish: 'el agua', english: 'the water', gender: 'el', icon: 'water' },
      { id: 'item-milk', spanish: 'la leche', english: 'the milk', gender: 'la', icon: 'milk' },
    ],
    explanation: '"Las naranjas" is feminine plural.',
  },

  // =========================================================================
  // 4. CAFÉ, PLEASE PROMPTS
  // =========================================================================
  {
    id: 'cfe.order.cafe-con-leche.1',
    revision: 1,
    game: 'cafe',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    customerName: 'Elena',
    orderSpokenSpanish: 'Quería un café con leche, por favor.',
    orderEnglish: 'I would like a coffee with milk, please.',
    targetSlot: {
      drink: 'café',
      milk: 'con leche',
      quantity: 1,
    },
    explanation: 'Elena asked for 1 café con leche.',
  },
  {
    id: 'cfe.order.cortado.1',
    revision: 1,
    game: 'cafe',
    targetId: 'order.modifier',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    customerName: 'Carlos',
    orderSpokenSpanish: 'Un cortado, por favor.',
    orderEnglish: 'A cortado (espresso with dash of milk), please.',
    targetSlot: {
      drink: 'cortado',
      milk: 'cortado',
      quantity: 1,
    },
    explanation: 'Carlos ordered 1 cortado.',
  },
  {
    id: 'cfe.order.dos-cafes.1',
    revision: 1,
    game: 'cafe',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    customerName: 'Sofía',
    orderSpokenSpanish: 'Dos cafés solos, por favor.',
    orderEnglish: 'Two black coffees, please.',
    targetSlot: {
      drink: 'café',
      milk: 'solo',
      quantity: 2,
    },
    explanation: 'Sofía ordered 2 cafés solos (black coffees).',
  },

  // =========================================================================
  // 5. SPOT THE SLIP PROMPTS
  // =========================================================================
  {
    id: 'slp.past.gerund.1',
    revision: 1,
    game: 'slip',
    targetId: 'past.progressive-action',
    chapterId: 'chapter-b',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    sentence: 'Ayer estaba cocinar cuando llamaste.',
    tokens: ['Ayer', 'estaba', 'cocinar', 'cuando', 'llamaste.'],
    hasError: true,
    errorTokenIndex: 2, // 'cocinar'
    correctionChoices: ['cocinando', 'cocinó', 'cocina'],
    correctCorrection: 'cocinando',
    correctedSentence: 'Ayer estaba cocinando cuando llamaste.',
    explanation: 'After "estar", use the gerund (-ando/-iendo): "estaba cocinando", never the infinitive.',
  },
  {
    id: 'slp.hypo.tendria.1',
    revision: 1,
    game: 'slip',
    targetId: 'hypo.time-money',
    chapterId: 'chapter-c',
    evidence: 'meaning-recognition',
    supportLevel: 'stretch',
    sentence: 'Si tendría más tiempo, viajaría más.',
    tokens: ['Si', 'tendría', 'más', 'tiempo,', 'viajaría', 'más.'],
    hasError: true,
    errorTokenIndex: 1, // 'tendría'
    correctionChoices: ['tuviera', 'tengo', 'tuve'],
    correctCorrection: 'tuviera',
    correctedSentence: 'Si tuviera más tiempo, viajaría más.',
    explanation: 'Never use the conditional ("tendría") directly following "si" for hypothetical conditions. Use the imperfect subjunctive ("tuviera").',
  },
  {
    id: 'slp.order.gender.1',
    revision: 1,
    game: 'slip',
    targetId: 'order.table',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    sentence: 'Quiero un mesa para dos personas.',
    tokens: ['Quiero', 'un', 'mesa', 'para', 'dos', 'personas.'],
    hasError: true,
    errorTokenIndex: 1, // 'un'
    correctionChoices: ['una', 'el', 'la'],
    correctCorrection: 'una',
    correctedSentence: 'Quiero una mesa para dos personas.',
    explanation: '"Mesa" is feminine, so it requires the feminine article: "una mesa".',
  },
  {
    id: 'slp.past.valid-no-error.1',
    revision: 1,
    game: 'slip',
    targetId: 'past.simultaneous',
    chapterId: 'chapter-b',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    sentence: 'Mientras yo cocinaba, él ponía la mesa.',
    tokens: ['Mientras', 'yo', 'cocinaba,', 'él', 'ponía', 'la', 'mesa.'],
    hasError: false,
    errorTokenIndex: -1,
    correctionChoices: ['Sentence is correct as is'],
    correctCorrection: 'Sentence is correct as is',
    correctedSentence: 'Mientras yo cocinaba, él ponía la mesa.',
    explanation: 'This sentence is already completely correct! Two simultaneous ongoing actions in the imperfect.',
  },

  // =========================================================================
  // 6. WHAT DID THEY MEAN? (LISTENING / IMPLICATION)
  // =========================================================================
  {
    id: 'lsn.order.preference.1',
    revision: 1,
    game: 'listening',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'listening-recognition',
    supportLevel: 'supported',
    clipSpanish: 'Perdona, quería pedir la cuenta cuando puedas.',
    transcript: 'Perdona, quería pedir la cuenta cuando puedas.',
    question: 'What is the customer asking for?',
    choices: [
      { id: 'c1', text: 'To pay the bill when the waiter has a moment', isCorrect: true },
      { id: 'c2', text: 'To order another coffee right now', isCorrect: false },
      { id: 'c3', text: 'To see the dessert menu', isCorrect: false },
    ],
    explanation: '"Quería pedir la cuenta cuando puedas" is a polite request to bring the bill.',
  },
  {
    id: 'lsn.past.event-order.1',
    revision: 1,
    game: 'listening',
    targetId: 'past.progressive-interrupt',
    chapterId: 'chapter-b',
    evidence: 'listening-recognition',
    supportLevel: 'standard',
    clipSpanish: 'Cuando llegué a su casa, todavía estaban cenando.',
    transcript: 'Cuando llegué a su casa, todavía estaban cenando.',
    question: 'What was the order of events?',
    choices: [
      { id: 'c1', text: 'Dinner was already in progress when the speaker arrived.', isCorrect: true },
      { id: 'c2', text: 'They started having dinner after the speaker arrived.', isCorrect: false },
      { id: 'c3', text: 'They had already finished dinner before the speaker arrived.', isCorrect: false },
    ],
    explanation: '"Todavía estaban cenando" tells us dinner was currently ongoing when "llegué" occurred.',
  },
  {
    id: 'lsn.hypo.stance.1',
    revision: 1,
    game: 'listening',
    targetId: 'hypo.advice',
    chapterId: 'chapter-c',
    evidence: 'listening-recognition',
    supportLevel: 'stretch',
    clipSpanish: 'Si fuera tú, no le diría nada hasta mañana.',
    transcript: 'Si fuera tú, no le diría nada hasta mañana.',
    question: 'What is the speaker advising?',
    choices: [
      { id: 'c1', text: 'Waiting until tomorrow before saying anything', isCorrect: true },
      { id: 'c2', text: 'Speaking up immediately tonight', isCorrect: false },
      { id: 'c3', text: 'Cancelling the meeting completely', isCorrect: false },
    ],
    explanation: '"Si fuera tú, no le diría nada hasta mañana" means "If I were you, I wouldn\'t say anything until tomorrow".',
  },
];
