import { AnyPrompt } from '../types';

export const ALL_PROMPTS: AnyPrompt[] = [
  // =========================================================================
  // 1. METRO SPRINT / PHRASE BUILDER PROMPTS
  // =========================================================================
  {
    id: 'bld.order.bill.1',
    revision: 2,
    game: 'builder',
    targetId: 'order.bill',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Ask for the bill politely at the counter.',
    intentEs: 'Pide la cuenta en la barra con educación.',
    situationalContext: 'Terminas tu consumición en la barra y quieres pagar antes de irte.',
    interlocutorQuestion: 'Camarero: «¿Desea algo más, jefe?»',
    tiles: [
      { id: 't1', text: 'La' },
      { id: 't2', text: 'cuenta,' },
      { id: 't3', text: 'por' },
      { id: 't4', text: 'favor.' },
      { id: 't5', text: 'el' },
      { id: 't6', text: 'café' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'La cuenta, por favor.',
    explanation: 'Usa "La cuenta, por favor" o "¿Me cobras, por favor?" para pedir la cuenta con naturalidad.',
  },
  {
    id: 'bld.order.item.1',
    revision: 2,
    game: 'builder',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Order a coffee, please.',
    intentEs: 'Pide un café solo con cortesía.',
    situationalContext: 'Llegas a la barra del bar por la mañana y saludas al camarero.',
    interlocutorQuestion: 'Camarero: «¡Buenas! ¿Qué va a ser?»',
    tiles: [
      { id: 't1', text: 'Un' },
      { id: 't2', text: 'café,' },
      { id: 't3', text: 'por' },
      { id: 't4', text: 'favor.' },
      { id: 't5', text: 'una' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'Un café, por favor.',
    explanation: '"Café" es masculino: "Un café, por favor".',
  },
  {
    id: 'bld.order.polite.1',
    revision: 2,
    game: 'builder',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Order a white coffee using the natural Madrid bar formula.',
    intentEs: 'Pide un café con leche usando la fórmula estándar en barra española.',
    situationalContext: 'Estás en la barra y te atienden directamente.',
    interlocutorQuestion: 'Camarero: «Dime, salao, ¿qué te pongo?»',
    tiles: [
      { id: 't1', text: 'Ponme' },
      { id: 't2', text: 'un' },
      { id: 't3', text: 'café' },
      { id: 't4', text: 'con' },
      { id: 't5', text: 'leche,' },
      { id: 't6', text: 'por' },
      { id: 't7', text: 'favor.' },
      { id: 't8', text: 'Quería' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6', 't7'],
      ['t8', 't2', 't3', 't4', 't5', 't6', 't7'],
    ],
    validOffTargetSequences: [
      {
        sequence: ['t8', 't2', 't3', 't4', 't5', 't6', 't7'],
        feedback: '¡Válido! Pero en la barra de un bar en España escucharás mucho más directo: "¡Ponme un café!".',
      },
    ],
    canonicalDisplay: 'Ponme un café con leche, por favor.',
    explanation: 'En España, "Ponme..." es la fórmula más cálida, directa y habitual al pedir en la barra.',
  },
  {
    id: 'bld.order.table.1',
    revision: 2,
    game: 'builder',
    targetId: 'order.table',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Request a table for two people.',
    intentEs: 'Pide mesa para dos personas en la terraza.',
    situationalContext: 'Llegas a un restaurante concurrido de La Latina y te atiende el metre.',
    interlocutorQuestion: 'Camarero: «¡Hola! ¿Buscabais sitio?»',
    tiles: [
      { id: 't1', text: 'Una' },
      { id: 't2', text: 'mesa' },
      { id: 't3', text: 'para' },
      { id: 't4', text: 'dos,' },
      { id: 't5', text: 'por' },
      { id: 't6', text: 'favor.' },
      { id: 't7', text: 'un' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
    ],
    canonicalDisplay: 'Una mesa para dos, por favor.',
    explanation: '"Mesa" es femenino: "Una mesa para dos, por favor."',
  },

  // Chapter B: What was happening? (Builder)
  {
    id: 'bld.past.interrupt.1',
    revision: 2,
    game: 'builder',
    targetId: 'past.progressive-interrupt',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Explain what you were doing when your friend interrupted with a phone call.',
    intentEs: 'Explica qué estabas haciendo cuando te llamó tu amigo.',
    situationalContext: 'Tu amigo te pregunta por qué tardaste tanto en contestar.',
    interlocutorQuestion: 'Amigo: «Oye, ¿por qué no cogiste el teléfono antes?»',
    tiles: [
      { id: 't1', text: 'Estaba' },
      { id: 't2', text: 'estudiando' },
      { id: 't3', text: 'cuando' },
      { id: 't4', text: 'llamaste.' },
      { id: 't5', text: 'llamabas' },
      { id: 't6', text: 'estudié' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4'],
    ],
    canonicalDisplay: 'Estaba estudiando cuando llamaste.',
    explanation: 'La acción de fondo continua usa "estaba estudiando", y el hecho puntual que interrumpe usa pretérito indefinido: "llamaste".',
  },
  {
    id: 'bld.past.action.1',
    revision: 2,
    game: 'builder',
    targetId: 'past.progressive-action',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    intent: 'Tell your roommate what you were doing in the kitchen.',
    intentEs: 'Dile a tu compañera de piso qué hacías en la cocina.',
    situationalContext: 'Tu compañera nota olor a comida recién hecha y te pregunta.',
    interlocutorQuestion: 'Compañera: «¡Mmm, qué bien huele! ¿Qué hacías?»',
    tiles: [
      { id: 't1', text: 'Estaba' },
      { id: 't2', text: 'cocinando.' },
      { id: 't3', text: 'Era' },
      { id: 't4', text: 'cocinar' },
    ],
    acceptedSequences: [
      ['t1', 't2'],
    ],
    canonicalDisplay: 'Estaba cocinando.',
    explanation: 'El pretérito imperfecto progresivo se forma con estar (estaba) + gerundio (cocinando).',
  },
  {
    id: 'bld.past.group.1',
    revision: 2,
    game: 'builder',
    targetId: 'past.progressive-group',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Explain what you and your friends were doing late last night.',
    intentEs: 'Explica qué estabais haciendo todo el grupo anoche.',
    situationalContext: 'Te preguntan qué hacía el grupo a las diez de la noche en el restaurante.',
    interlocutorQuestion: 'Amigo: «¿Qué estabais haciendo a esa hora?»',
    tiles: [
      { id: 't1', text: 'Estábamos' },
      { id: 't2', text: 'cenando.' },
      { id: 't3', text: 'Cenamos' },
      { id: 't4', text: 'Estaban' },
    ],
    acceptedSequences: [
      ['t1', 't2'],
    ],
    canonicalDisplay: 'Estábamos cenando.',
    explanation: '"Nosotros estábamos cenando" expresa una actividad de grupo en progreso.',
  },

  // Chapter C: If I had more time… (Builder)
  {
    id: 'bld.hypo.time.1',
    revision: 2,
    game: 'builder',
    targetId: 'hypo.time-money',
    chapterId: 'chapter-c',
    evidence: 'scaffolded-production',
    supportLevel: 'stretch',
    intent: 'Express what you would do if you had more free time.',
    intentEs: 'Expresa qué harías si tuvieras más tiempo libre.',
    situationalContext: 'Estás soñando despierto con tus próximas vacaciones ideales.',
    interlocutorQuestion: 'Colega: «Si tuvieras un mes libre, ¿qué harías?»',
    tiles: [
      { id: 't1', text: 'Si' },
      { id: 't2', text: 'tuviera' },
      { id: 't3', text: 'más' },
      { id: 't4', text: 'tiempo,' },
      { id: 't5', text: 'viajaría' },
      { id: 't6', text: 'más.' },
      { id: 't7', text: 'tengo' },
      { id: 't8', text: 'viajo' },
      { id: 't9', text: 'tuviese' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
      ['t1', 't9', 't3', 't4', 't5', 't6'],
    ],
    canonicalDisplay: 'Si tuviera más tiempo, viajaría más.',
    explanation: 'Oración condicional irreal: "Si + imperfecto de subjuntivo (tuviera/tuviese)" + "condicional (viajaría)".',
  },
  {
    id: 'bld.hypo.advice.1',
    revision: 2,
    game: 'builder',
    targetId: 'hypo.advice',
    chapterId: 'chapter-c',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    intent: 'Offer friendly advice using the "If I were you" formula.',
    intentEs: 'Dale un consejo amistoso a tu colega sobre su situación.',
    situationalContext: 'Tu amigo duda sobre si hablar con su jefa o callarse.',
    interlocutorQuestion: 'Amigo: «No sé qué hacer... ¿qué me aconsejas?»',
    tiles: [
      { id: 't1', text: 'Si' },
      { id: 't2', text: 'fuera' },
      { id: 't3', text: 'tú,' },
      { id: 't4', text: 'hablaría' },
      { id: 't5', text: 'con' },
      { id: 't6', text: 'ella.' },
      { id: 't7', text: 'era' },
      { id: 't8', text: 'fuese' },
    ],
    acceptedSequences: [
      ['t1', 't2', 't3', 't4', 't5', 't6'],
      ['t1', 't8', 't3', 't4', 't5', 't6'],
    ],
    canonicalDisplay: 'Si fuera tú, hablaría con ella.',
    explanation: '"Si fuera tú, hablaría..." o "Yo que tú..." es la fórmula natural para aconsejar en español peninsular.',
  },

  // =========================================================================
  // 2. AVENTURAS EN MADRID (BRANCHING STORY DIALOGUES)
  // =========================================================================
  {
    id: 'tls.cafe.counter.1',
    revision: 2,
    game: 'tales',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    title: 'Mañana en la barra',
    setting: 'Una bulliciosa barra de Madrid con aroma a café recién molido y tostadas crujientes.',
    explanation: 'Pedir en la barra del bar requiere fórmulas cálidas y directas como "Ponme un café" y "¿Me cobras?".',
    turns: [
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: '¡Buenos días! ¿Qué va a ser?',
        goal: 'Order a coffee with milk politely.',
        goalEs: 'Pide un café con leche usando la fórmula natural de barra.',
        choices: [
          {
            id: 'c1',
            text: '¡Ponme un café con leche, por favor!',
            isCorrect: true,
            feedback: '¡Perfecto! Tono directo, cálido y auténtico de barra.',
            consequence: 'El camarero asiente con una sonrisa rápida y enciende la máquina de espresso.',
          },
          {
            id: 'c2',
            text: 'Solo un vaso de agua del grifo, gracias.',
            isCorrect: false,
            isOffTarget: true,
            feedback: 'El camarero te servirá agua, pero querías pedir un café con leche.',
            consequence: 'El camarero te sirve un vaso de agua fría y espera.',
          },
        ],
      },
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: '¿Algo para picar? ¿Un cruasán o una tostada con tomate?',
        goal: 'Ask for toast with tomato.',
        goalEs: 'Pide una tostada con tomate.',
        choices: [
          {
            id: 'c3',
            text: 'Una tostada con tomate, por favor.',
            isCorrect: true,
            feedback: 'Excelente elección: el desayuno clásico madrileño.',
            consequence: 'Corta el pan de barra y lo pone a tostar crujiente.',
          },
          {
            id: 'c4',
            text: 'Nada de comer hoy, solo el café.',
            isCorrect: false,
            isOffTarget: true,
            feedback: 'Decides no comer nada, aunque la tostada con tomate era tu objetivo.',
            consequence: 'El camarero retira la cesta de pan con un gesto rápido.',
          },
        ],
      },
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: 'Aquí tienes todo. ¿Deseas algo más?',
        goal: 'Ask for the bill.',
        goalEs: 'Pide la cuenta para marcharte.',
        choices: [
          {
            id: 'c5',
            text: 'Nada más. ¿Me cobras cuando puedas?',
            isCorrect: true,
            feedback: 'Fórmula impecable para pedir la cuenta en barra.',
            consequence: 'Te deja el platito con el tique: «Son tres euros con cincuenta, majo».',
          },
          {
            id: 'c6',
            text: 'Paso luego a pagar mañana.',
            isCorrect: false,
            feedback: '¡En un bar nuevo no te fiarán la cuenta!',
            consequence: 'El camarero te mira con incredulidad y te señala el datáfono.',
          },
        ],
      },
    ],
  },
  {
    id: 'tls.metro.meeting.1',
    revision: 2,
    game: 'tales',
    targetId: 'past.progressive-interrupt',
    chapterId: 'chapter-b',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    title: 'Encuentro en el Metro de Sol',
    setting: 'El andén de la Línea 1 en hora punta, lleno de trenes llegando y gente con prisa.',
    explanation: 'Usa "estaba sacando" para la acción continua en el andén y "llamaste" para la llamada que te interrumpió.',
    turns: [
      {
        speaker: 'Marta',
        speakerRole: 'friend',
        text: '¡Oye! ¿Dónde estabas metido? ¡Te estuve llamando!',
        goal: 'Explain you were buying a train pass when she called.',
        goalEs: 'Explica que estabas sacando el billete cuando llamó.',
        choices: [
          {
            id: 'c1',
            text: 'Estaba sacando el billete cuando llamaste.',
            isCorrect: true,
            feedback: '¡Exacto! "Estaba sacando" (acción continua) + "llamaste" (interrupción).',
            consequence: 'Marta guarda el móvil: «Ah, vale, con el lío de las máquinas se tarda un siglo».',
          },
          {
            id: 'c2',
            text: 'Compré el billete y después llamé.',
            isCorrect: false,
            feedback: 'Eso no explica la llamada que perdiste mientras hacías la cola.',
            consequence: 'Marta se encoge de hombros: «Bueno, lo importante es que estás aquí».',
          },
        ],
      },
      {
        speaker: 'Marta',
        speakerRole: 'friend',
        text: '¿Hacemos transbordo en Tribunal o vamos directos en autobús?',
        goal: 'Suggest changing trains at Tribunal.',
        goalEs: 'Sugiere hacer transbordo en Tribunal.',
        choices: [
          {
            id: 'c3',
            text: 'Mejor hacemos transbordo en Tribunal, es más rápido.',
            isCorrect: true,
            feedback: 'Propuesta práctica para moverse en el metro de Madrid.',
            consequence: 'Subís juntos al vagón justo antes de que pite el cierre de puertas.',
          },
          {
            id: 'c4',
            text: 'Nos vamos andando hasta Chamartín.',
            isCorrect: false,
            feedback: '¡Son más de seis kilómetros a pie!',
            consequence: 'Marta se ríe: «¡Ni locos, nos derretimos con este calor!».',
          },
        ],
      },
    ],
  },
  {
    id: 'tls.retiro.hypo.1',
    revision: 2,
    game: 'tales',
    targetId: 'hypo.advice',
    chapterId: 'chapter-c',
    evidence: 'meaning-recognition',
    supportLevel: 'stretch',
    title: 'Tarde de confidencias en El Retiro',
    setting: 'Un banco a la sombra de los castaños cerca del Palacio de Cristal.',
    explanation: '"Si fuera tú, me lo pensaría" combina el subjuntivo con el condicional para dar consejo sin imponer.',
    turns: [
      {
        speaker: 'Javi',
        speakerRole: 'friend',
        text: 'Tengo un dilema... Me han ofrecido un trabajo en Barcelona, pero mi vida entera está en Madrid.',
        goal: 'Give tactful advice using the hypothetical advice structure.',
        goalEs: 'Dale un consejo amistoso con la estructura de hipótesis ("Si fuera tú...").',
        choices: [
          {
            id: 'c1',
            text: 'Si fuera tú, me lo pensaría muy bien antes de decidir.',
            isCorrect: true,
            feedback: 'Consejo prudente y fórmula condicional impecable.',
            consequence: 'Javi asiente aliviado: «Tienes razón, no voy a precipitarme».',
          },
          {
            id: 'c2',
            text: 'Vete ya mismo hoy sin avisar.',
            isCorrect: false,
            feedback: 'Demasiado impulsivo y poco empático.',
            consequence: 'Javi sacude la cabeza: «No puedo dejarlo todo colgado así».',
          },
        ],
      },
      {
        speaker: 'Javi',
        speakerRole: 'friend',
        text: '¿Y qué harías si te pidieran empezar este mismo lunes?',
        goal: 'Express what you would do in that situation.',
        goalEs: 'Expresa qué harías tú en esa tesitura con el condicional.',
        choices: [
          {
            id: 'c3',
            text: 'Les pediría al menos dos semanas de margen.',
            isCorrect: true,
            feedback: 'Uso perfecto del condicional ("pediría") para responder a una hipótesis.',
            consequence: 'Javi sonríe: «Eso es lo justo. Voy a negociar ese plazo».',
          },
          {
            id: 'c4',
            text: 'Pido dinero ahora mismo.',
            isCorrect: false,
            feedback: 'No concuerda con la hipótesis planteada.',
            consequence: 'Javi frunce el ceño: «No me refiero al dinero, sino al tiempo».',
          },
        ],
      },
    ],
  },
  {
    id: 'tls.tapas.chueca.1',
    revision: 2,
    game: 'tales',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    title: 'Tapeo de fin de semana',
    setting: 'Una taberna tradicional de paredes de azulejos en Chueca, con pizarra de raciones.',
    explanation: '"Caña" es la medida estándar de cerveza de grifo en Madrid, servida con buena crema.',
    turns: [
      {
        speaker: 'Camarero',
        speakerRole: 'server',
        text: '¡Oído al fondo! ¿Qué os marcho para beber?',
        goal: 'Order two draught beers and a sparkling water.',
        goalEs: 'Pide dos cañas y un agua con gas.',
        choices: [
          {
            id: 'c1',
            text: 'Ponme dos cañas y un agua con gas, por favor.',
            isCorrect: true,
            feedback: '¡Clavado! Vocabulario castizo con "cañas" y petición natural.',
            consequence: 'Tira las dos cañas con dos dedos de crema y abre el botellín de agua.',
          },
          {
            id: 'c2',
            text: 'Queremos dos litros de leche caliente.',
            isCorrect: false,
            feedback: 'En una taberna de tapeo nadie pide leche caliente.',
            consequence: 'El camarero te mira perplejo: «Aquí servimos cañas y vino, amigo».',
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 3. MERCADO RUSH (MADRID MARKET STALL)
  // =========================================================================
  {
    id: 'mkt.order.bread.1',
    revision: 2,
    game: 'market',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Add the bread to the market bag.',
    instructionEs: 'Pon el pan recién hecho en la bolsa.',
    vendorDialogue: '«Dime, salao, ¿te pongo una barrita de pan bien crujiente?»',
    correctItemId: 'item-bread',
    choices: [
      { id: 'item-cheese', spanish: 'el queso', english: 'the cheese', gender: 'el', icon: 'cheese', weightGrams: 250 },
      { id: 'item-bread', spanish: 'el pan', english: 'the bread', gender: 'el', icon: 'bread', weightGrams: 300 },
      { id: 'item-milk', spanish: 'la leche', english: 'the milk', gender: 'la', icon: 'milk', weightGrams: 1000 },
    ],
    explanation: '"Pan" es masculino en español: "el pan".',
  },
  {
    id: 'mkt.order.water.1',
    revision: 2,
    game: 'market',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'standard',
    instruction: 'Add the water bottle to the bag.',
    instructionEs: 'Añade la botella de agua a la bolsa.',
    vendorDialogue: '«¡Para la sed! ¿Te pongo el botellín de agua?»',
    correctItemId: 'item-water',
    choices: [
      { id: 'item-water', spanish: 'el agua', english: 'the water', gender: 'el', icon: 'water', weightGrams: 500 },
      { id: 'item-orange', spanish: 'las naranjas', english: 'the oranges', gender: 'las', icon: 'orange', weightGrams: 1000 },
      { id: 'item-apple', spanish: 'la manzana', english: 'the apple', gender: 'la', icon: 'apple', weightGrams: 200 },
    ],
    explanation: '"Agua" toma el artículo masculino en singular para evitar choque vocálico: "el agua".',
  },
  {
    id: 'mkt.order.cheese.1',
    revision: 2,
    game: 'market',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Add the cured cheese wedge to the bag.',
    instructionEs: 'Pon la cuña de queso manchego en la cesta.',
    vendorDialogue: '«¿Te corto un cuarto de kilo de queso manchego curado?»',
    correctItemId: 'item-cheese',
    choices: [
      { id: 'item-bread', spanish: 'el pan', english: 'the bread', gender: 'el', icon: 'bread', weightGrams: 300 },
      { id: 'item-cheese', spanish: 'el queso', english: 'the cheese', gender: 'el', icon: 'cheese', weightGrams: 250 },
      { id: 'item-apple', spanish: 'la manzana', english: 'the apple', gender: 'la', icon: 'apple', weightGrams: 200 },
    ],
    explanation: '"Queso" es masculino: "el queso curado".',
  },
  {
    id: 'mkt.order.oranges.1',
    revision: 2,
    game: 'market',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'meaning-recognition',
    supportLevel: 'supported',
    instruction: 'Add the bag of fresh oranges.',
    instructionEs: 'Pon las naranjas de Valencia en la báscula.',
    vendorDialogue: '«¡Están dulcísimas las naranjas hoy! ¿Te pongo un kilo?»',
    correctItemId: 'item-orange',
    choices: [
      { id: 'item-orange', spanish: 'las naranjas', english: 'the oranges', gender: 'las', icon: 'orange', weightGrams: 1000 },
      { id: 'item-water', spanish: 'el agua', english: 'the water', gender: 'el', icon: 'water', weightGrams: 500 },
      { id: 'item-milk', spanish: 'la leche', english: 'the milk', gender: 'la', icon: 'milk', weightGrams: 1000 },
    ],
    explanation: '"Las naranjas" es femenino plural: "las naranjas".',
  },

  // =========================================================================
  // 4. BARISTA DE BARRIO (MADRID BAR SIMULATOR)
  // =========================================================================
  {
    id: 'cfe.order.cafe-con-leche.1',
    revision: 2,
    game: 'cafe',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    customerName: 'Elena (La Latina)',
    orderSpokenSpanish: '¡Ponme un café con leche, por favor!',
    orderEnglish: 'Put me a white coffee, please (authentic bar order).',
    targetSlot: {
      drink: 'café',
      milk: 'con leche',
      quantity: 1,
    },
    explanation: 'Elena ha pedido 1 café con leche en barra.',
  },
  {
    id: 'cfe.order.cortado.1',
    revision: 2,
    game: 'cafe',
    targetId: 'order.modifier',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    customerName: 'Carlos (Malasaña)',
    orderSpokenSpanish: '¡Oye, jefe! Ponme un cortado con leche fría, porfa.',
    orderEnglish: 'Hey bartender! Put me an espresso with a splash of cold milk.',
    targetSlot: {
      drink: 'cortado',
      milk: 'cortado',
      quantity: 1,
    },
    explanation: 'Carlos pidió 1 cortado (café con una nube de leche fría).',
  },
  {
    id: 'cfe.order.dos-cafes.1',
    revision: 2,
    game: 'cafe',
    targetId: 'order.quantity',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    customerName: 'Sofía y Lucas (Chueca)',
    orderSpokenSpanish: '¡Buenas! Ponme dos cafés solos con hielo, cuando puedas.',
    orderEnglish: 'Hi! Put me two black coffees with ice, whenever you can.',
    targetSlot: {
      drink: 'café',
      milk: 'solo',
      quantity: 2,
    },
    explanation: 'Sofía pidió 2 cafés solos con hielo.',
  },

  // =========================================================================
  // 5. TAPEO FRENZY (MADRID TAPAS DISPATCH)
  // =========================================================================
  {
    id: 'tpo.order.bravas.1',
    revision: 1,
    game: 'tapeo',
    targetId: 'order.item',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    patronName: 'Marcos (Bar La Paloma)',
    orderSpokenSpanish: '¡Oído, jefe! Ponme unas patatas bravas y una caña bien fría.',
    orderEnglish: 'Order up! Put me some patatas bravas and an ice-cold draught beer.',
    requiredItemIds: ['bravas', 'cana'],
    availableItems: [
      { id: 'bravas', nameEs: 'Patatas bravas', nameEn: 'Spicy potatoes', icon: '🥔', category: 'tapa' },
      { id: 'cana', nameEs: 'Caña bien tirada', nameEn: 'Draught beer', icon: '🍺', category: 'bebida' },
      { id: 'tortilla', nameEs: 'Pincho de tortilla', nameEn: 'Spanish omelette', icon: '🍳', category: 'tapa' },
      { id: 'croquetas', nameEs: 'Croquetas de jamón', nameEn: 'Ham croquettes', icon: '🥟', category: 'tapa' },
    ],
    explanation: 'Marcos pidió una ración de patatas bravas y una caña de cerveza.',
  },
  {
    id: 'tpo.order.tortilla.1',
    revision: 1,
    game: 'tapeo',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'scaffolded-production',
    supportLevel: 'supported',
    patronName: 'Lucía (Taberna San Ginés)',
    orderSpokenSpanish: '¡Buenas! Ponme un pincho de tortilla poco cuajada y un botellín de agua.',
    orderEnglish: 'Hi! Put me a slice of runny Spanish omelette and a bottle of water.',
    requiredItemIds: ['tortilla', 'agua'],
    availableItems: [
      { id: 'tortilla', nameEs: 'Pincho de tortilla', nameEn: 'Spanish omelette', icon: '🍳', category: 'tapa' },
      { id: 'agua', nameEs: 'Botellín de agua', nameEn: 'Bottle of water', icon: '💧', category: 'bebida' },
      { id: 'calamares', nameEs: 'Bocata de calamares', nameEn: 'Calamari sub', icon: '🥖', category: 'tapa' },
      { id: 'vino', nameEs: 'Copa de Rioja', nameEn: 'Red wine', icon: '🍷', category: 'bebida' },
    ],
    explanation: 'Lucía pidió un pincho de tortilla española y agua.',
  },
  {
    id: 'tpo.past.tapeo.1',
    revision: 1,
    game: 'tapeo',
    targetId: 'past.progressive-action',
    chapterId: 'chapter-b',
    evidence: 'scaffolded-production',
    supportLevel: 'standard',
    patronName: 'Carlos y amigos (Cervecería Retiro)',
    orderSpokenSpanish: '¡Estábamos esperando la comida! Ponme unas croquetas de jamón y una copa de Rioja.',
    orderEnglish: 'We were waiting for food! Put me ham croquettes and a glass of red wine.',
    requiredItemIds: ['croquetas', 'vino'],
    availableItems: [
      { id: 'croquetas', nameEs: 'Croquetas de jamón', nameEn: 'Ham croquettes', icon: '🥟', category: 'tapa' },
      { id: 'vino', nameEs: 'Copa de Rioja', nameEn: 'Red wine', icon: '🍷', category: 'bebida' },
      { id: 'bravas', nameEs: 'Patatas bravas', nameEn: 'Spicy potatoes', icon: '🥔', category: 'tapa' },
      { id: 'cana', nameEs: 'Caña bien tirada', nameEn: 'Draught beer', icon: '🍺', category: 'bebida' },
    ],
    explanation: 'La comanda incluye croquetas de jamón caseras y vino tinto.',
  },
  {
    id: 'tpo.hypo.tapeo.1',
    revision: 1,
    game: 'tapeo',
    targetId: 'hypo.situation',
    chapterId: 'chapter-c',
    evidence: 'scaffolded-production',
    supportLevel: 'stretch',
    patronName: 'David (Plaza Mayor)',
    orderSpokenSpanish: 'Si tuvierais calamares recién fritos, me comería dos... ¡Ponme un bocadillo de calamares y una caña!',
    orderEnglish: 'If you had freshly fried calamari, I would eat two... Put me a calamari sandwich and a draught beer!',
    requiredItemIds: ['calamares', 'cana'],
    availableItems: [
      { id: 'calamares', nameEs: 'Bocadillo de calamares', nameEn: 'Calamari sandwich', icon: '🥖', category: 'tapa' },
      { id: 'cana', nameEs: 'Caña bien tirada', nameEn: 'Draught beer', icon: '🍺', category: 'bebida' },
      { id: 'tortilla', nameEs: 'Pincho de tortilla', nameEn: 'Spanish omelette', icon: '🍳', category: 'tapa' },
      { id: 'bravas', nameEs: 'Patatas bravas', nameEn: 'Spicy potatoes', icon: '🥔', category: 'tapa' },
    ],
    explanation: 'El cliente pidió el clásico madrileño: bocata de calamares con su caña.',
  },

  // =========================================================================
  // 6. RADIO RETIRO / ESCUCHA URBANA (LISTENING & DEDUCTION)
  // =========================================================================
  {
    id: 'lsn.order.preference.1',
    revision: 2,
    game: 'listening',
    targetId: 'order.polite',
    chapterId: 'chapter-a',
    evidence: 'listening-recognition',
    supportLevel: 'supported',
    clipSpanish: '¡Oye, perdona! ¿Me cobras cuando puedas?',
    transcript: '¡Oye, perdona! ¿Me cobras cuando puedas?',
    question: 'What is the customer asking the waiter for?',
    questionEs: '¿Qué le está pidiendo el cliente al camarero?',
    choices: [
      {
        id: 'c1',
        text: 'To pay the bill when the waiter has a moment',
        textEs: 'Pagar la consumición en cuanto el camarero tenga un momento',
        isCorrect: true,
      },
      {
        id: 'c2',
        text: 'To order another round of drinks right now',
        textEs: 'Pedir otra ronda de bebidas inmediatamente',
        isCorrect: false,
      },
      {
        id: 'c3',
        text: 'To see the dessert menu',
        textEs: 'Ver la carta de postres',
        isCorrect: false,
      },
    ],
    explanation: '"¿Me cobras cuando puedas?" es la fórmula más cotidiana y natural para pedir la cuenta en un bar en España.',
  },
  {
    id: 'lsn.past.event-order.1',
    revision: 2,
    game: 'listening',
    targetId: 'past.progressive-interrupt',
    chapterId: 'chapter-b',
    evidence: 'listening-recognition',
    supportLevel: 'standard',
    clipSpanish: 'Cuando llegué a su casa de Malasaña, todavía estaban cenando.',
    transcript: 'Cuando llegué a su casa de Malasaña, todavía estaban cenando.',
    question: 'What was the relationship between the two events?',
    questionEs: '¿Qué relación temporal hubo entre ambos acontecimientos?',
    choices: [
      {
        id: 'c1',
        text: 'Dinner was already in progress when the speaker arrived.',
        textEs: 'La cena ya estaba en marcha cuando llegó la persona que habla.',
        isCorrect: true,
      },
      {
        id: 'c2',
        text: 'They started preparing dinner after the speaker arrived.',
        textEs: 'Empezaron a preparar la cena después de su llegada.',
        isCorrect: false,
      },
      {
        id: 'c3',
        text: 'They had completely finished dinner before anyone got there.',
        textEs: 'Ya habían terminado de cenar mucho antes.',
        isCorrect: false,
      },
    ],
    explanation: '"Todavía estaban cenando" indica que la acción de cenar continuaba en pleno desarrollo cuando ocurrió "llegué".',
  },
  {
    id: 'lsn.hypo.stance.1',
    revision: 2,
    game: 'listening',
    targetId: 'hypo.advice',
    chapterId: 'chapter-c',
    evidence: 'listening-recognition',
    supportLevel: 'stretch',
    clipSpanish: 'Si fuera tú, no le diría nada hasta mañana por la mañana.',
    transcript: 'Si fuera tú, no le diría nada hasta mañana por la mañana.',
    question: 'What is the speaker advising?',
    questionEs: '¿Qué le aconseja la persona a su interlocutor?',
    choices: [
      {
        id: 'c1',
        text: 'Waiting until tomorrow before saying anything',
        textEs: 'Esperar hasta mañana por la mañana antes de hablar',
        isCorrect: true,
      },
      {
        id: 'c2',
        text: 'Calling right now tonight in the heat of the moment',
        textEs: 'Llamar de inmediato esta noche en caliente',
        isCorrect: false,
      },
      {
        id: 'c3',
        text: 'Never mentioning the issue again forever',
        textEs: 'No volver a hablar del tema jamás',
        isCorrect: false,
      },
    ],
    explanation: '"Si fuera tú, no le diría nada hasta mañana" aconseja prudencia y esperar a la mañana siguiente.',
  },
];
